#!/usr/bin/env python3
"""
scripts/lite/sync-kernel.py
Dynamically generates CLAUDE.md, AGENTS.md, and GEMINI.md from kernel files
to eliminate duplication, drift, and ensure boot context remains under 7k tokens.
"""

import os
import argparse
import re
import stat
import sys
import tempfile

# Find project root
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.abspath(os.path.join(SCRIPT_DIR, "..", ".."))
KERNEL_DIR = os.path.join(PROJECT_ROOT, "kernel")
LITE_FILES = [
    "ENTRY.md",
    "SOLVE.md",
    "VERIFY.md",
    "ESCALATE.md",
    "CLARIFY.md",
    "POLICY.md",
]

TARGETS = {
    "CLAUDE.md": {
        "title": "# Forgewright Kernel LITE — Claude Code",
        "description": "This file is read by Claude Code on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "AGENTS.md": {
        "title": "# Forgewright Kernel LITE — Antigravity / Cursor",
        "description": "This file is read by Antigravity / Cursor on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
    "GEMINI.md": {
        "title": "# Forgewright Kernel LITE — Gemini",
        "description": "This file is read by Gemini on every new chat. It defines the core rules, boot sequence, and solving loop.",
    },
}


def estimate_tokens(text):
    # Deterministic token estimation
    return len(text) // 4


def _read_kernel() -> str:
    print(f"Reading kernel files from: {KERNEL_DIR}")
    kernel_contents = []

    for filename in LITE_FILES:
        filepath = os.path.join(KERNEL_DIR, filename)
        if not os.path.exists(filepath):
            raise FileNotFoundError(filepath)

        with open(filepath, "r", encoding="utf-8") as f:
            content = f.read().strip()
            # Clean up links to kernel files so agents don't try to reread them
            content = re.sub(
                r"\[kernel/([A-Z]+)\.md\]\([^)]+\)", r"\1 section", content
            )
            kernel_contents.append(
                f"<!-- START OF {filename} -->\n{content}\n<!-- END OF {filename} -->"
            )

    combined_kernel = "\n\n".join(kernel_contents)
    total_kernel_tokens = estimate_tokens(combined_kernel)
    print(f"Kernel source files estimate: {total_kernel_tokens} tokens")
    return combined_kernel


def _target_content(target_name, info, combined_kernel, existing=""):
    # Preserve post-kernel sections (e.g., GitNexus) from existing file.
    preserved_sections = ""
    if existing:
        # Find all <!-- marker:start --> ... <!-- marker:end --> blocks.
        for marker in ["gitnexus", "forgenexus"]:
            pattern = rf"(<!-- {marker}:start -->.*?<!-- {marker}:end -->)"
            match = re.search(pattern, existing, re.DOTALL)
            if match:
                preserved_sections += "\n" + match.group(1) + "\n"

    content = f"""{info["title"]}

> **DO NOT EDIT THIS FILE DIRECTLY.** It is dynamically generated by the sync script.
> Source of truth resides in the `kernel/` directory. Run `python3 scripts/lite/sync-kernel.py` to regenerate.

{info["description"]}

---

{combined_kernel}
{preserved_sections}"""
    return content, preserved_sections


def _atomic_write(target_path, content):
    """Replace one generated file atomically after a complete local write."""
    target_path = os.path.abspath(target_path)
    parent = os.path.dirname(target_path)
    mode = (
        stat.S_IMODE(os.stat(target_path).st_mode)
        if os.path.exists(target_path)
        else 0o644
    )
    fd, temporary = tempfile.mkstemp(
        prefix=f".{os.path.basename(target_path)}.", dir=parent
    )
    try:
        with os.fdopen(fd, "w", encoding="utf-8") as handle:
            handle.write(content)
            handle.flush()
            os.fsync(handle.fileno())
        os.chmod(temporary, mode)
        os.replace(temporary, target_path)
    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass
        raise


def sync(check=False):
    """Generate instruction files, or check drift without writing any file.

    ``check=True`` intentionally performs only reads and comparisons. It is
    suitable for startup hooks and CI drift checks where mutation is unsafe.
    """
    try:
        combined_kernel = _read_kernel()
    except FileNotFoundError as error:
        print(f"Error: Required kernel file '{error.args[0]}' does not exist.")
        return 1

    has_error = False
    has_drift = False
    for target_name, info in TARGETS.items():
        target_path = os.path.join(PROJECT_ROOT, target_name)
        existing = ""
        if os.path.exists(target_path):
            with open(target_path, "r", encoding="utf-8") as f:
                existing = f.read()
        content, preserved_sections = _target_content(
            target_name, info, combined_kernel, existing
        )
        if check:
            if not existing:
                print(f"Drift: {target_name} is missing.")
                has_drift = True
            elif existing != content:
                print(f"Drift: {target_name} differs from kernel sources.")
                has_drift = True
        else:
            _atomic_write(target_path, content)

        target_tokens = estimate_tokens(content)
        status = "OK" if target_tokens < 7000 else "EXCEEDED LIMIT"
        preserved_note = (
            " (preserved post-kernel sections)" if preserved_sections else ""
        )
        print(
            f"Generated: {target_name} ({target_tokens} est. tokens) -> [{status}]{preserved_note}"
        )

        if target_tokens >= 7000:
            print(
                f"Error: {target_name} exceeds the 7k deterministic token budget limit!",
                file=sys.stderr,
            )
            has_error = True

    if has_error:
        return 1
    if has_drift:
        return 1
    return 0


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="read-only drift check; never writes generated instruction files",
    )
    raise SystemExit(sync(check=parser.parse_args().check))
